### ISSUE TITLE
🐛 Bug Report: Scroll Top button is missing in team page

### ISSUE THREAD

**Issue by devXprite** [novuhq/hacksquad-website#101]
### 📜 Description

Scroll to Top button is missing from team page

### 👟 Reproduction steps

1. Go to leaderboard https://www.hacksquad.dev/leaderboard
2. Click on any team name

### 👍 Expected behavior

There should be  a scroll button in team page.

### 👎 Actual Behavior with Screenshots

n/a

### 💻 Operating system

Linux

### 🤖 Node Version

16

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by devXprite** [comment]
Hii @TheLearneer can i work on this issue ?

**Comment by TheLearneer** [comment]
You can always create a PR to help us make the website better.
However with the time constrain and lots of events happening in the last week, I can't promise if the PR will get be reviewed and merged for Hacktoberfest 🙏
