### ISSUE TITLE
Typo: Grammatical error in Hover connection box for dev.to

### ISSUE THREAD

**Issue by mstomar698** [novuhq/hacksquad-website#102]
### 📜 Description

Just a typo in line 1.

### 👟 Reproduction steps

Change line 1.

### 👍 Expected behavior

Without grammatical error

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/89572392/197377408-9732cedc-0669-4b89-83ed-20c829e2845b.png)

### 💻 Operating system

Windows

### 🤖 Node Version

14x

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by vedant-z** [comment]
@mstomar698 i want to take this issue
