### ISSUE TITLE
Typo: Grammatical error in Notification Setting

### ISSUE THREAD

**Issue by bandya2003** [novuhq/hacksquad-website#105]
### 📜 Description

In the Notification Settings :

announcement 

disqualified 

winner 

The initial alphabets need to be Capitalised.

### 👟 Reproduction steps

Make the changes according to the description.

### 👍 Expected behavior

Without grammatical error

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/61108642/197818659-0ec76f5a-4686-4d1a-a37f-829054976db3.png)

### 💻 Operating system

Windows

### 🤖 Node Version

16.17.0

### 📃 Provide any additional context for the Bug.

None

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by vedant-z** [comment]
@bandya2003 Please assign me, i wanna work on this

**Comment by HengKevin** [comment]
Can I work on this?

**Comment by TheLearneer** [comment]
Thank you for the issue report.
We are not assigning the grammar and typo fixes to anyone 🙏
