### ISSUE TITLE
Leave team

### ISSUE THREAD

**Issue by geisterfurz007** [novuhq/hacksquad-website#11]
I was wondering if it was possible to leave a team again; I just wanted to peek around and had myself assign to a random team and afterwards thought it would make sense to join forces with a couple of my colleagues but now it appears I am stuck in the randomly assigned team.

I am not sure what the implications would be if someone left a team since I am not really familiar with the domain but maybe that is something that could be added? I would be down to give it a shot if that was something that could be done :)

**Comment by nevo-david** [comment]
We will add an ability to exit a team after maximum 2 days when you join :)

**Comment by geisterfurz007** [comment]
I saw this today and could successfully leave the team; thanks a bunch!

**Comment by rover07** [comment]
I created a team, now I want to disband/remove members. I can't as of now, will it be possible to do so?
