### ISSUE TITLE
Create custom 404 page.

### ISSUE THREAD

**Issue by nirajpdn** [novuhq/hacksquad-website#114]
Suggestions:
* It would be better if we create  custom 404 page for better user experience in the site. 
* If we enter wrong path or route it is showing default `Next.js` 404 page.
* It would be better if we show some information and `Go to home` link from the 404 page.

**Comment by nirajpdn** [comment]
@nevo-david @TheLearneer , what's your take on this ?

**Comment by TheLearneer** [comment]
Hi @nirajpdn 👋 

The designs for the website are made entirely by a dedicated team, thus I believe we are not looking for contribution from the community on this one.
