### ISSUE TITLE
Beautiful alert on send message

### ISSUE THREAD

**Issue by rahmat-st** [novuhq/hacksquad-website#12]
Now the information when we send a message still uses the default alert from javascript, can I help you to update it with a beautiful alert?

**Comment by rahmat-st** [comment]
![image](https://user-images.githubusercontent.com/40190205/193452194-2acdd0ba-90be-411e-8f2e-d96afaeaf27e.png)

I can't push @nevo-david

**Comment by nevo-david** [comment]
You have to create a new fork and push it there!

**Comment by rahmat-st** [comment]
oh sorry, I forgot to fork first 😅

**Comment by rahmat-st** [comment]
I've create the pull request #15

can it be hacktoberfest PR?
