### ISSUE TITLE
🚀 Feature:  Background of squad name 

### ISSUE THREAD

**Issue by himanshu1221** [novuhq/hacksquad-website#129]
### 🔖 Feature description

- Background of the squad name is like the following 
![Screenshot from 2023-09-20 17-29-25](https://github.com/novuhq/hacksquad-website/assets/32031706/8d3df3a5-99d7-4c4b-b427-ef0fe55d138f)

- Background of the squad name can be none it will enhance the UI Of the website 
![Screenshot from 2023-09-20 17-37-17](https://github.com/novuhq/hacksquad-website/assets/32031706/974de58a-55a4-400e-8282-0c63a693651c)

### 🎤 Why is this feature needed ?

This will enhance the UI of the website

### ✌️ How do you aim to achieve this?

I will fix the CSS

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Archit5655** [comment]
Working on it

**Comment by vijayn838** [comment]
can you assign this task to me?

**Comment by krittt** [comment]
Can you assign this to me ?

**Comment by Vanshi2504ka** [comment]
Kindly assign me this issue

**Comment by Abinanthan47** [comment]
I can able to solve this issue, assign me...

**Comment by dev-soni-07** [comment]
Dear Contributors, 

Join my team on Hackquad and HacktoberFest 2023. 1 contribution will count for both Hacksquad and HacktoberFest. Increase your chances of winning certificates and swags from both the contests.

https://www.hacksquad.dev/invite/cln8n87c80011mn06bjd8f1f3

**Comment by Sumit-910** [comment]
Please assign this to me

**Comment by bsantosh909** [comment]
Thank you for mentioning it, however we are not looking for this change 🙏
