### ISSUE TITLE
🚀 Feature: 

### ISSUE THREAD

**Issue by Archit5655** [novuhq/hacksquad-website#135]
### 🔖 Feature description

To add a contribution guide  in readme.md or a separate Contribution.md file  mentioning 
-How to set up the project in the local  environment.

### 🎤 Why is this feature needed ?

To let the beginners know how to setup this project locally.

### ✌️ How do you aim to achieve this?

Either create a Contribution.md file or add to the readme.md file .

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by mpatwa98** [comment]
I would like to work on this. Can you assign it to me?

**Comment by Anju-Narnolia** [comment]
I would like to work on this issue. Please assign it to me.
