### ISSUE TITLE
🐛 Bug Report:  No padding in footer

### ISSUE THREAD

**Issue by himanshu1221** [novuhq/hacksquad-website#139]
### 📜 Description

When i was surfing thru the website i saw there is nno magin and padding as well in the footer 
![Screenshot from 2023-09-23 09-55-39](https://github.com/novuhq/hacksquad-website/assets/32031706/6568fb7a-7e94-46c9-9279-02f69948bc26)

### 👟 Reproduction steps

go to my sqad page and check out the footer

### 👍 Expected behavior

there should be a margin and a  padding in the footer

### 👎 Actual Behavior with Screenshots

![Screenshot from 2023-09-23 09-55-39](https://github.com/novuhq/hacksquad-website/assets/32031706/2344dd87-b563-40b0-988d-344c34177deb)

### 💻 Operating system

Linux

### 🤖 Node Version

18.17.1

### 📃 Provide any additional context for the Bug.

there padding can be added in the footer it will enhance the website 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by adarsh-jha-dev** [comment]
I will be pleased if you assign me this work

**Comment by bsantosh909** [comment]
Thanks for the report @himanshu1221 
However this should now be fixed as of the new design changes.
