### ISSUE TITLE
🚀 Feature :  Documentation and PR feature at Front Page

### ISSUE THREAD

**Issue by HarshShinde0** [novuhq/hacksquad-website#140]
### 🔖 Feature description

Documentation and PR feature at Front Page before the  " Welcome to Hacksquad "

![image](https://github.com/novuhq/hacksquad-website/assets/113786425/19d03183-26e5-44c9-9a8e-ea17d7a71f39)

### 🎤 Why is this feature needed ?

this will easily highlighted to people so they can direct got github at start working on it.

### ✌️ How do you aim to achieve this?

I have Team who will help and do this task ASAP.

### 🔄️ Additional Information

in this there will be small 1 line  info about Hacksquad program and PR link on the Page

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sujitmahapatra** [comment]
I have Team who will help and do this task ASAP.

**Comment by HarshShinde0** [comment]
My Squad is also waiting to do this task
