### ISSUE TITLE
Can We Add Animated Lines Under The Navbar Links Whenever Someone Hover It ?

### ISSUE THREAD

**Issue by AhzamAkhtar** [novuhq/hacksquad-website#16]
![pls](https://user-images.githubusercontent.com/94620460/193457440-6dd429a5-55d2-497c-8e05-260d576cd54e.png)

**Comment by nevo-david** [comment]
@scopsy @lnikell  what do you think?

**Comment by scopsy** [comment]
I think I prefer the existing subtle color change as opposed to adding underline.
