### ISSUE TITLE
[Bug] Cannot send message to your squad through mobile !!

### ISSUE THREAD

**Issue by sumitbishti** [novuhq/hacksquad-website#18]
1. The "send" button is not visible for mobile users and neither are you able to send message through "enter" button.

![Screenshot (34)](https://user-images.githubusercontent.com/75713174/193461718-8152d36f-1562-4200-90cc-84764bd130c3.png)

2. Please add some margin at the bottom.

![Screenshot (35)](https://user-images.githubusercontent.com/75713174/193461821-29a04b3a-0d08-421a-9215-96148672aa43.png)

3. Is the lowercase intentional ?

![Screenshot (36)](https://user-images.githubusercontent.com/75713174/193462023-3fb5f6da-805d-4628-8e2c-6b7994fd579c.png)

**Comment by nevo-david** [comment]
Do you want to fix it? :)

**Comment by sumitbishti** [comment]
Yes!!

**Comment by nevo-david** [comment]
Go for it :)

**Comment by sumitbishti** [comment]
In order to fix this i need to sign in to the site. But how do i to that here?
![Screenshot (38)](https://user-images.githubusercontent.com/75713174/193879233-6682094f-6919-4ff0-b69e-330cbefa8b79.png)

**Comment by diwash007** [comment]
@sumitbishti , May I work on this issue?

**Comment by Anushka123-star** [comment]
Still can't send messages to teammates on the mobile plus problems in hovering
