### ISSUE TITLE
🚀 Feature:  Adding contributors section to the Readme.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [novuhq/hacksquad-website#182]
### 🔖 Feature description

There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
Any contributions make are greatly appreciated, for that we need to add new section for contributors and adding to the readme file!

### 🎤 Why is this feature needed ?

The "Contributors" section in a README file is important, it serves as a way to acknowledge and express gratitude to those who have contributed to an open-source project. It also fosters transparency, showing that the project is a collaborative effort, which can build trust and credibility. Additionally, it motivates contributors, as seeing their names listed provides recognition and can encourage ongoing involvement. 

### ✌️ How do you aim to achieve this?

By adding a contributors section in Readme.md file, I can update as much as better!
![contributors](https://github.com/novuhq/hacksquad-website/assets/147402107/a2464aaf-0380-4315-b4ae-7fbde3c3f8a3)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Kalyanimhala** [comment]
Kindly  #182 assign me this issue, I want to work on it.

**Comment by bsantosh909** [comment]
Thank you for the report @Kalyanimhala 
However this feels a little out of scope from the project itself 🙏

**Comment by Kalyanimhala** [comment]
okay no issues! thanks for reply
