### ISSUE TITLE
🚀 Feature:  Inclusion of Light and Dark mode

### ISSUE THREAD

**Issue by Akshat111111** [novuhq/hacksquad-website#184]
### 🔖 Feature description

Inclusion of Light and Dark mode 

### 🎤 Why is this feature needed ?

It will make the user interface more attractive.

### ✌️ How do you aim to achieve this?

Using addition of a new function.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ankitsharma495** [comment]
can you please assign me this issue. i want to make contribution for hacktoberfest23.

**Comment by bsantosh909** [comment]
@Akshat111111 Theme switch for HackSquad website doesn't make any sense because we have a specific design. 🙏
