### ISSUE TITLE
🚀 Feature: Scroll to top

### ISSUE THREAD

**Issue by bilalmirza74** [novuhq/hacksquad-website#204]
### 🔖 Feature description

After reaching the footer, instead of scrolling back up by rotating the mouse wheel or swiping on mobile, we can simply click on the scroll-to-top button.

### 🎤 Why is this feature needed ?

Adding a Scroll to Top Button can improve/enhance UX/UI

### ✌️ How do you aim to achieve this?

yes

### 🔄️ Additional Information

![image](https://github.com/novuhq/hacksquad-website/assets/84387676/23a3d284-ad6d-401b-8d6c-7f2c2492db30)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by bilalmirza74** [comment]
assign me this 
i like to work on this

**Comment by Himanshu99001** [comment]
I like to work on this issue
