### ISSUE TITLE
🐛 Bug Report: Link incorrect in Q&A section

### ISSUE THREAD

**Issue by tmsagarofficial** [novuhq/hacksquad-website#205]
### 📜 Description

The link in this Question : **How do we calculate the score?** is wrong or not linked to an appropriate resource.

### 👟 Reproduction steps

1. Go to https://www.hacksquad.dev/#qa
2. Check the question `How do we calculate the score?`
3. Check the link with the link text `found here`
4. Click on it

### 👍 Expected behavior

A link pointing to an appropriate resource.

### 👎 Actual Behavior with Screenshots

<img width="638" alt="image" src="https://github.com/novuhq/hacksquad-website/assets/110724849/0a206eb0-bfa4-4518-9ac7-30f363afb614">

### 💻 Operating system

Windows

### 🤖 Node Version

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by bsantosh909** [comment]
Thanks for the report @tmsagarofficial 
However the link is actually properly linked to correct resource. 🙏

**Comment by tmsagarofficial** [comment]
Pls check again @TheLearneer 


That link points to https://github.com/novuhq/hacksquad-background/blob/main/src/services/github/github.service.ts

<img width="646" alt="image" src="https://github.com/novuhq/hacksquad-website/assets/110724849/0a7f9e5e-a561-43e5-bae0-af91b6123b3a">

**Comment by bsantosh909** [comment]
@tmsagarofficial yes it does, and that is the correct file as well.
All the logic behind which PRs have been accepted or rejected, lies there

**Comment by tmsagarofficial** [comment]
Ohh ok i thought this should lead to some text-based resource on how the calculation works.

**Comment by tmsagarofficial** [comment]
Sorry for the trouble
