### ISSUE TITLE
Add bottom margin

### ISSUE THREAD

**Issue by AnshuPathak-88825** [novuhq/hacksquad-website#23]
Current 
![Screenshot (21)](https://user-images.githubusercontent.com/78332454/193512780-e4a5ec91-930d-4855-808a-b21f171172d6.png)
what change I want to do
![Screenshot (22)](https://user-images.githubusercontent.com/78332454/193512850-1f29e8e2-32e6-4971-85d0-58282f63ab5d.png)
want to add some bottom margin because currently it is not looking good icons touching bottom

**Comment by AnshuPathak-88825** [comment]
@nevo-david pls assign me this issue

**Comment by nevo-david** [comment]
We have a PR on this already :(
