### ISSUE TITLE
Rank of the team display in my squad page

### ISSUE THREAD

**Issue by AnshuPathak-88825** [novuhq/hacksquad-website#24]

**Comment by AnshuPathak-88825** [comment]
![image](https://user-images.githubusercontent.com/78332454/193514024-ba9fc7c5-f5b5-4114-9cc2-8cdab1c2524c.png)
team rank should be display on  this page

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by nevo-david** [comment]
Go for it! :)
