### ISSUE TITLE
Delete Member Feature

### ISSUE THREAD

**Issue by ImBIOS** [novuhq/hacksquad-website#3]
A pretty useful use case for deleting a member is when our member cannot be contacted or he/she is offline which makes our team feels less fun and enjoy the HackSquad event.

**Comment by nevo-david** [comment]
I am afraid people will abuse it,
What do you think about letting the owner to kick members within 1 day?

**Comment by ImBIOS** [comment]
I think we need to have a cooldown or something like that. After thinking your opinion, It also make sense for me. Some mechanism should protect from someone to abuse it.

**Comment by nevo-david** [comment]
So... Can you do it? ❤️

**Comment by ImBIOS** [comment]
I think I'm able to do it. But, is it okay if it delivered in October?

**Comment by nevo-david** [comment]
Beginning? :)

**Comment by ImBIOS** [comment]
Yup, It will be a joke when I deliver it in the end of October 😂😂😂

**Comment by nevo-david** [comment]
Awesome! Assigning it to you :)

**Comment by ImBIOS** [comment]
Sorry, I think can't deliver it on time.

**Comment by nevo-david** [comment]
:(
