### ISSUE TITLE
Duplicate team name

### ISSUE THREAD

**Issue by rahmat-dev** [novuhq/hacksquad-website#32]
I think you need to add an "update" team name button for the best experience and also when I change my team name with another team name, I can do it. It will be duplicated.

Do you need to fix it? Can I work for it?

**Comment by rahmat-st** [comment]
![image](https://user-images.githubusercontent.com/40190205/193607057-7e86e5f1-5988-4019-a60b-54945a8f83b0.png)

**Comment by nevo-david** [comment]
Sure go for it!
