### ISSUE TITLE
Kick AFK teammates

### ISSUE THREAD

**Issue by rahmat-dev** [novuhq/hacksquad-website#35]
For reason that teammates do not participate in a team, maybe this feature can be implemented on your website

**Comment by nevo-david** [comment]
Can you define AFK?

**Comment by rahmat-st** [comment]
Teammates who don't make Pull Requests or contribute to the team

**Comment by nevo-david** [comment]
Period of time?

**Comment by rahmat-st** [comment]
1 week maybe
