### ISSUE TITLE
Report and issue

### ISSUE THREAD

**Issue by nevo-david** [novuhq/hacksquad-website#48]
Allow users to report issues for PRs. When there is more than 3 report over a PR, it will write "Flagged" next to the PR and send a Novu notification to the moderators.

**Comment by DhruvLamba** [comment]
Hello Sir, I want to work on it. 
In this issue do I have to make a seperate reporting button

**Comment by TheLearneer** [comment]
Hello @DhruvLamba 👋 
yes we need a report button, but on top of that we also need to add the functionality on the backend as well.

Basically what we would need to do is:
- Added a button on the frontend to report a PR
- Added information about how many users reported the PR on the backend
  - We will need to store who exactly reported the PR for spam prevention and also to disable the report button for the specific PR on the frontend
- After a PR gets 3 report we need to send notification to the moderators (through Novu)
- Also add a page where moderators can see the reported PRs and take actions against those PRs

**Comment by DhruvLamba** [comment]
Okay sir I will work on it. Thankyou

**Comment by TheLearneer** [comment]
Alright, assigning it to you then 🙏

**Comment by DhruvLamba** [comment]
Thankyou Sir
