### ISSUE TITLE
add a moving glowing RGB scroll to the website.

### ISSUE THREAD

**Issue by vedant-3010** [novuhq/hacksquad-website#51]
Something like this. It will really go well with the theme of the website.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/92071471/194078289-461fad23-60b9-473d-aa79-7e4768092be7.png">

can I do it ?

**Comment by nevo-david** [comment]
Haha, what do you think @andrewgolovanov

**Comment by andrewgolovanov** [comment]
@nevo-david Looks like the designers won't be able to sleep well after this :upside_down_face:
But I'll still talk to the designers about it and get their opinion, and then I'll give you feedback.

**Comment by dare-devilll** [comment]
Did I say something wrong? Because it feels like I did.😅

**Comment by ComBarnea** [comment]
Haha @dare-devilll 🤣 @andrewgolovanov is part of our design team. They call the shots on everything that is design. Let's see what they come up with :)

**Comment by anshulsoni2010** [comment]
@dare-devilll, Hi sir, I am able to do it, Please assign me.I will do in 5-6minute

**Comment by andrewgolovanov** [comment]
Unfortunately, the design team thinks this isn't a good idea - we might have expected that :sweat_smile:
