### ISSUE TITLE
[issue] Both the buttons do the same thing.

### ISSUE THREAD

**Issue by vedant-3010** [novuhq/hacksquad-website#52]
Is it a bug or a feature?
I think it's not good according to UX.

<img width="224" alt="image" src="https://user-images.githubusercontent.com/92071471/194081991-d7301f3b-bbd6-4552-adb8-a542bb0f6590.png">

**Comment by nevo-david** [comment]
I think it's a problem because of the responsiveness. We might need to remove this button on mobile. Do you want to work on it?

**Comment by dare-devilll** [comment]
Yes.

**Comment by viveknshah** [comment]
@nevo-david are we looking to remove the button or simply hide it in the responsiveness? 

Assuming @media tag for min-width to show that button? Because in the desktop, it does make sense for both to exist .

**Comment by dare-devilll** [comment]
@viveknshah We need to hide it in the mobile version.

**Comment by viveknshah** [comment]
> @viveknshah We need to hide it in the mobile version.

Wouldnt setting the min width for showing the button solve the same? Below that defined size it won't show.

**Comment by NwaforAugustine321** [comment]
@nevo-david I want to know if the problem is still available for fixing, let me work on it
