### ISSUE TITLE
Show personal score

### ISSUE THREAD

**Issue by kailashchoudhary11** [novuhq/hacksquad-website#57]
Users should also be able to see their personal scores! Currently one needs to count the number of PR's made by him/her.

**Comment by nevo-david** [comment]
It's a little tricky because we don't save the personal score at the moment.
Need to add another field to the DB save the score in show it.
Are you up to it?

**Comment by kailashchoudhary11** [comment]
I don't think I will be able to do it all alone.

**Comment by andrewdoro** [comment]
hey @kailashchoudhary11 I could work with you on this

**Comment by MitAbhay** [comment]
I would like to work on this issue @nevo-david !! Assign me

**Comment by mishmanners** [comment]
I would love this ❤️
