### ISSUE TITLE
bug: cannot find notification bell button with mobile view

### ISSUE THREAD

**Issue by abhilipsasahoo03** [novuhq/hacksquad-website#58]
Bugs in Mobile View:

- Cannot find notification button to look into recent notifications. 

![Screenshot_2022-10-06-16-35-10-387_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/194299170-fc5c0f28-c658-4fa9-a81b-bdc8d91a22b5.jpg)
![Screenshot_2022-10-06-16-47-12-717_com.android.chrome.jpg](https://user-images.githubusercontent.com/80174214/194299521-64d6ead5-4c81-4d6b-8faa-d745812045b2.jpg)

**Comment by anirudhp26** [comment]
Hey there, I would like to contribute to this issue ! 
@abhilipsasahoo03

**Comment by abhilipsasahoo03** [comment]
> Hey there, I would like to contribute to this issue ! 
> @abhilipsasahoo03 

Sure thing, but ask one of the maintainers to assign the issue to you first!

**Comment by anirudhp26** [comment]
Okay, Should I start working on the issue?

**Comment by abhilipsasahoo03** [comment]
> Okay, Should I start working on the issue? 

Sure thing! Meanwhile tag some maintainers to let them know.

**Comment by nevo-david** [comment]
Do you want to put it next to the burger menu @anirudhp26?

**Comment by anirudhp26** [comment]
Yeah, I was planning to do that only

**Comment by carefreeav09** [comment]
I would like to work on this issue.
