### ISSUE TITLE
feature: show github avatar instead of the github logo

### ISSUE THREAD

**Issue by washbin** [novuhq/hacksquad-website#59]
In the myteam page, can we show real github avatar of corresponding users instead of the generic github logo ?
Some pictures may appear a little cranky due to the small size, while some may appear kool.
I guess this is something to be discussed with UI team as well .

If this a feature that could be included I would be happy to work on it.

**Comment by ShrutiRani7029** [comment]
HEY, THIS ISSUE IS FULL OF EXCITEMENT WITH INNOVATION, AND I WANT TO CONTRIBUTE TO THIS, CAN YOU PLEASE ASSIGN THIS TO ME?

**Comment by washbin** [comment]
Hello, So I am not one of the maintainers of the repository, I am just a fellow contributor like you and was willing to work if it was a desirable feature. Seems like @nevo-david missed this issue though.
