### ISSUE TITLE
mobile screen nav top button.

### ISSUE THREAD

**Issue by PGautam27** [novuhq/hacksquad-website#60]
This is the issue. I would like work on this.
![WhatsApp Image 2022-10-07 at 6 00 15 PM](https://user-images.githubusercontent.com/92343715/194553786-3971599d-ecc8-4d73-94a1-4a00fefcc11e.jpeg)

**Comment by PGautam27** [comment]
Would you assign it to me.

**Comment by TheLearneer** [comment]
Solved with #74
