### ISSUE TITLE
Footer alignment in my squad screen 

### ISSUE THREAD

**Issue by PGautam27** [novuhq/hacksquad-website#61]
The footer in my squad screen is quite off alignment. I would like to rectify it. Would you assign it to me.

![Screenshot 2022-10-07 183815](https://user-images.githubusercontent.com/92343715/194561333-f05d0eaf-fd7d-4046-b37d-00652c34632a.png)

**Comment by nevo-david** [comment]
Go for it!

**Comment by kabir0x23** [comment]
Hello @nevo-david , Can you assign me to this task
It's been 5 days, no response
- my pr is ready
![image](https://user-images.githubusercontent.com/44284877/195609922-57455e51-02ba-4a66-959d-c2b9a491a0e6.png)

Thank you

**Comment by kabir0x23** [comment]
Fest is going to end in 17 days, if we keep delaying this, there will be no use later, 
And improper layout doesn't look good, so i have made a pr

**Comment by PriyansuMaurya** [comment]
@nevo-david, Why this issue's pull request was not merged?

![image](https://github.com/novuhq/hacksquad-website/assets/101447544/2ed993bb-a5d4-40e9-8215-5284e1c6f414)


It is definitely required!

**Comment by 0xk4b1r** [comment]
> @nevo-david, Why this issue's pull request was not merged?
> 
> ![image](https://user-images.githubusercontent.com/101447544/269389239-2ed993bb-a5d4-40e9-8215-5284e1c6f414.png)
> 
> It is definitely required!

inactive repo

i have done the pr above, but they didnt merge , so i have removed it.

u can try u can create a new pr

**Comment by PriyansuMaurya** [comment]
yeah, I will try. let's see what happens?
