### ISSUE TITLE
docs: Add issue templates and pr template 

### ISSUE THREAD

**Issue by shashankbhatgs** [novuhq/hacksquad-website#65]
## Description 
It would be nice to have a template for raising new issues and also for the pull requests so that it'll be structured and easy for folks contributing to this project. 

## Solution

I would like to add the templates for issues and the pull request.

**Comment by shashankbhatgs** [comment]
also if you think this issue is valid, what are the points should be mentioned in the templates. Shall I use templates of novu/novu project?  @nevo-david

**Comment by nevo-david** [comment]
Can you do it? :)

**Comment by shashankbhatgs** [comment]
@nevo-david  making a folder .github and then adding those templates inside this folder right?

**Comment by nevo-david** [comment]
To be honest, I don't know @scopsy, @davidsoderberg, @ainouzgali, @djabarovgeorge, @p-fernandez can help you out.
