### ISSUE TITLE
finding the team's position in the leaderboard

### ISSUE THREAD

**Issue by saimaheshtaduri** [novuhq/hacksquad-website#66]
possible solutions : 
1. adding a search functionality in leaderboard page can help folks search their team's position easily
2. highlight one's team in the table
3. scroll to one's own team when leaderboard page is opened.

Implementing one of the above solution can easily let folks find their team position in the leaderboard.

**Comment by nevo-david** [comment]
Can you work on it? :)

**Comment by saimaheshtaduri** [comment]
Yes. I will, please assign to me @nevo-david

**Comment by DhruvLamba** [comment]
Can you please assign me this issue.

**Comment by tanvi1110** [comment]
yeah finding it quite difficult to search our team position

**Comment by 0xSaksham** [comment]
I think this issue has never been worked on. I want to work on this @nevo-david, as a part of HackSquad 2023.
