### ISSUE TITLE
add github link in hacksquad website

### ISSUE THREAD

**Issue by saimaheshtaduri** [novuhq/hacksquad-website#67]
Just realised there is no github link of this repo in the website. 
I found an enhancement and thought of raising an issue but then found there is no github link in the website. so had to google it. 
Having a github link might be of some use to other folks too.

@nevo-david

**Comment by saimaheshtaduri** [comment]
@nevo-david

**Comment by nevo-david** [comment]
Sounds good! can you work on it?

**Comment by saimaheshtaduri** [comment]
can I start working on this ? @nevo-david
