### ISSUE TITLE
Suggestion: CSS spacing 

### ISSUE THREAD

**Issue by FidalMathew** [novuhq/hacksquad-website#8]
On the leaderboards page, the social icons don't have any spacing below them. 

I feel it would look better if the social icons were placed a little above the end of the website.

Current website:
![image](https://user-images.githubusercontent.com/84982038/193404510-e383fc23-a549-42be-88eb-255ae250bb72.png)

Desired result:
![image](https://user-images.githubusercontent.com/84982038/193404659-0dc10f31-8bd8-43dc-a1bc-71b7a7458581.png)

Let me know if the changes are required :)

**Comment by FidalMathew** [comment]
@nevo-david could you look into this ☺?

**Comment by nevo-david** [comment]
Yes! Go for it! :)

**Comment by jessej-samuel** [comment]
@FidalMathew  #14 might help with the issue you are facing when adding classes

**Comment by Manethpak** [comment]
Hi, if this issue has yet to be resolve, I would love to work on this!
