### ISSUE TITLE
Accordion for Q&A

### ISSUE THREAD

**Issue by Ruchita1010** [novuhq/hacksquad-website#83]
Currently, the Q&A is rendered as a list and we need to scroll a lot to find a particular question. I think an accordion would be much better as it will make it easier to go through the Q&A.

**Comment by jessej-samuel** [comment]
> Currently, the Q&A is rendered as a list and we need to scroll a lot to find a particular question. I think an accordion would be much better as it will make it easier to go through the Q&A.

I agree! In case this issue is approved, I'm willing to work on it :)

**Comment by nevo-david** [comment]
Agreed, it's the second PR we are getting about it though :)
Thank you for the support @Ruchita1010
