### ISSUE TITLE
🐛 Bug Report: Bonuses table items alignment issue

### ISSUE THREAD

**Issue by najeebkp** [novuhq/hacksquad-website#86]
#### Issue : Alignment issue in table rows

please assign me this. i can take care of it.

![Screenshot from 2022-10-13 11-55-44](https://user-images.githubusercontent.com/56462749/195518704-ffaac9cc-9abb-4685-b1fd-a61cca7c407b.png)

### 👟 Reproduction steps

1. Go to https://www.hacksquad.dev/bonuses

### 👍 Expected behavior

The table row elements should align center
![Screenshot from 2022-10-13 12-01-34](https://user-images.githubusercontent.com/56462749/195519389-b9a38cf6-8acb-433c-8900-8f4abdfadb2c.png)

### 👎 Actual Behavior with Screenshots

![Screenshot from 2022-10-13 11-55-44](https://user-images.githubusercontent.com/56462749/195518704-ffaac9cc-9abb-4685-b1fd-a61cca7c407b.png)

### 💻 Operating system

Linux

### 🤖 Node Version

16.14.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Anshul077** [comment]
hi i would like to solve this problem.
can i contribute?
