### ISSUE TITLE
🐛 Bug Report: Logo section at the bottom page overlap with mac's dock

### ISSUE THREAD

**Issue by Manethpak** [novuhq/hacksquad-website#92]
### 📜 Description

The Let's connect and Contribute section at the bottom page of /myteam is very hard to click on when you're on a mac since it will most likely overlap with the dock. See the video attached below

### 👟 Reproduction steps

1. Go to https://www.hacksquad.dev/myteam
2. Scroll to the bottom page

### 👍 Expected behavior

Should have some spacing at the bottom of the page. Also the github logo appear to be smaller than the others 2. 

### 👎 Actual Behavior with Screenshots

https://user-images.githubusercontent.com/58499300/196206768-dba9e482-36f5-46b1-be11-201e17205f93.mp4

### 💻 Operating system

MacOS

### 🤖 Node Version

16

### 📃 Provide any additional context for the Bug.

I want to work on this issue. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by TheLearneer** [comment]
Hi @Manethpak there is already an issue opened for it #8 🙏

**Comment by Manethpak** [comment]
@TheLearneer Oh, my bad! I didn't see the issue because the title were related to something else.
