### ISSUE TITLE
Leader controls

### ISSUE THREAD

**Issue by Shravan773** [novuhq/hacksquad-website#94]
### 🔖 Feature description

The team leader should have the permission or power to remove a person from  the group.

### 🎤 Why is this feature needed ?

If someone from the group is not contributing enough even after so much motivation or talks...the person should not be allowed to stay in group...and leader should have the power or permission to remove him..

### ✌️ How do you aim to achieve this?

Just give the leader the authority to remove or kick the person from the group

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

**Comment by TheLearneer** [comment]
Hello @Shravan773 it is intentional that leaders are not provided with this permissions due to various reasons.
For now, we kindly request you to communicate with Admin or Moderators on our Discord server.

Sorry for any inconvenience 🙏
