### ISSUE TITLE
🚀 Feature: Add Reponsiveness in 'myteam' page

### ISSUE THREAD

**Issue by devXprite** [novuhq/hacksquad-website#99]
### Current :-1:  :

![www hacksquad dev_myteam(vivo) (1)](https://user-images.githubusercontent.com/80192140/197318025-d39e4425-c7ea-4067-8ccc-d00bf218d260.png)

![www hacksquad dev_myteam(vivo) (4)](https://user-images.githubusercontent.com/80192140/197318082-67f3ad8b-bec2-40bb-a86e-036320f783ec.png)

### Expected :+1: :
![www hacksquad dev_myteam(vivo) (3)](https://user-images.githubusercontent.com/80192140/197318052-a93c29d0-5cda-491d-b918-9de30d9aae27.png)

![www hacksquad dev_myteam(vivo) (5)](https://user-images.githubusercontent.com/80192140/197318096-64b00f9d-b9c0-4c7a-85a6-d620ce01bfe0.png)

### 🎤 Why is this feature needed ?

I want to fix Input field,  Table and footer.

### ✌️ How do you aim to achieve this?

n/a

### 🔄️ Additional Information

Size: 360x760 px

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by diwash007** [comment]
#89

**Comment by Siva20021** [comment]
I can resolve this issue
